ci: new job added to compile with sanitizer flags

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -237,9 +237,14 @@ variables:
   git checkout $CUSTOM_DEBUG_BACKEND_TAG || git checkout $CI_COMMIT_REF_NAME || echo "using default branch"
   popd
   popd
+  export ASAN_OPTIONS=detect_invalid_pointer_pairs=2:print_stacktrace=1:strict_string_checks=1:halt_on_error=0:allocator_may_return_null=1 
   export PYTHONPATH=$PWD/${TEST_RUN_DIR}:$PWD/testing/esp/py_debug_backend
   . $PWD/${TEST_RUN_DIR}/gen_ut_app/gcov_data/gcov_env.sh
   testing/esp/run_tests.py -o $DIST_DIR/bin/openocd -s $DIST_DIR/share/openocd/scripts -a $PWD/$TEST_RUN_DIR -t xtensa-${CHIP_NAME}-elf- -d 4 -l $PWD/$TEST_RUN_DIR/debug_backend_tests.log -to $PWD/$TEST_RUN_DIR/results $TEST_RUN_EXTRA_OPTS
+  errors=$(grep -i -e".*sanitizer" -e"runtime error" ${TEST_RUN_DIR}/debug_backend_tests.log || true)
+  if [[ $errors ]]; then
+    echo "Sanitizer issues found!"; exit 0 #TODO exit 1 after all sanitizer errors fixed
+  fi
 
 .tests_linux_template: &tests_linux_template
   stage: test
@@ -324,6 +329,36 @@ build_linux_armel:
     - mkdir _build
     - pushd _build/
     - ../configure --prefix=$PWD/../$DIST_INSTALLED_DIR --host=${CONF_HOST}  $OPENOCD_CONFIGURE_OPTS
+    - make
+    - MAKEFLAGS= make install-strip
+    - popd
+    - *dist_archive
+
+build_linux_armel_test:
+  stage: build
+  image: $CI_DOCKER_REGISTRY/esp32-toolchain-arm-cross
+  tags:
+    - build
+  artifacts:
+    paths:
+      - ${DIST_ART_DIR}
+    reports:
+      junit:
+        - _build/*.log
+    when: always
+    expire_in: 2 weeks
+  variables:
+    CONF_HOST: "arm-linux-gnueabi"
+    PLATFORM_NAME: "armel-test"
+    TEST_CFLAGS: "-Wl,--no-as-needed -ldl -fsanitize=address -fsanitize=undefined -fsanitize-recover=address -ggdb3"
+  script:
+    - *get_release_name
+    - *add_gitlab_key
+    - *submodules_mirror_update
+    - ./bootstrap
+    - mkdir _build
+    - pushd _build/
+    - ../configure CFLAGS="${TEST_CFLAGS}" --prefix=$PWD/../$DIST_INSTALLED_DIR --host=${CONF_HOST}  $OPENOCD_CONFIGURE_OPTS
     - make
     - MAKEFLAGS= make install-strip
     - popd
@@ -488,10 +523,10 @@ tests_armel_esp32_solo:
     - test_jtag_solo
   dependencies:
     - build_test_app_esp32
-    - build_linux_armel
+    - build_linux_armel_test
   variables:
     CHIP_NAME: "esp32"
-    PLATFORM_NAME: "armel"
+    PLATFORM_NAME: "armel-test"
     TEST_RUN_DIR: "build_test_app_esp32"
     TEST_RUN_EXTRA_OPTS: "-i latest -b esp32-solo-devkitj -p test_*.*Single"
 
@@ -501,10 +536,10 @@ tests_armel_esp32_legacy_idf_rel:
     - test_jtag_arm
   dependencies:
     - build_test_app_esp32_legacy_idf_rel
-    - build_linux_armel
+    - build_linux_armel_test
   variables:
     CHIP_NAME: "esp32"
-    PLATFORM_NAME: "armel"
+    PLATFORM_NAME: "armel-test"
     TEST_RUN_DIR: "build_test_app_esp32_legacy_idf_rel"
     TEST_RUN_EXTRA_OPTS: "-i $TEST_APP_LEGACY_IDF_RELEASE_TAG -b esp32-wrover-kit-3.3v -e *.*Encrypted"
 
@@ -514,10 +549,10 @@ tests_armel_esp32_custom_idf_rel:
     - test_jtag_arm
   dependencies:
     - build_test_app_esp32_custom_idf_rel
-    - build_linux_armel
+    - build_linux_armel_test
   variables:
     CHIP_NAME: "esp32"
-    PLATFORM_NAME: "armel"
+    PLATFORM_NAME: "armel-test"
     TEST_RUN_DIR: "build_test_app_esp32_custom_idf_rel"
     # currently we need to run semihost test on IDF with old semihost driver
     TEST_RUN_EXTRA_OPTS: "-i $TEST_APP_CUSTOM_IDF_RELEASE_TAG -b esp32-wrover-kit-3.3v -p test_semihost -e *.*Encrypted"
@@ -528,10 +563,10 @@ tests_armel_esp32:
     - test_jtag_arm
   dependencies:
     - build_test_app_esp32
-    - build_linux_armel
+    - build_linux_armel_test
   variables:
     CHIP_NAME: "esp32"
-    PLATFORM_NAME: "armel"
+    PLATFORM_NAME: "armel-test"
     TEST_RUN_DIR: "build_test_app_esp32"
     TEST_RUN_EXTRA_OPTS: "-i latest -b esp32-wrover-kit-3.3v -e *.*Encrypted"
 
@@ -554,10 +589,10 @@ tests_armel_esp32s2:
     - test_jtag_arm_esp32s2
   dependencies:
     - build_test_app_esp32s2
-    - build_linux_armel
+    - build_linux_armel_test
   variables:
     CHIP_NAME: "esp32s2"
-    PLATFORM_NAME: "armel"
+    PLATFORM_NAME: "armel-test"
     TEST_RUN_DIR: "build_test_app_esp32s2"
     TEST_RUN_EXTRA_OPTS: "-i latest -b esp32s2-devkitj -p test_*.*Single"
 
@@ -690,14 +725,14 @@ test_nuttx_esp32:
   tags:
     - test_jtag_arm
   variables:
-    PLATFORM_NAME: "armel"
+    PLATFORM_NAME: "armel-test"
     TEST_RUN_DIR: "nuttx_test"
     NUTTX_APP_NAME: "nuttx_openocd"
     CHIP_NAME: "esp32"
     OOCD_CMDS: "set ESP_RTOS NuttX,set ESP32_ONLYCPU 1"
     TEST_RUN_EXTRA_OPTS: "-i other -b esp32-wrover-kit-3.3v -p test_nuttx -e *.*Encrypted"
   needs:
-    - job: build_linux_armel
+    - job: build_linux_armel_test
       artifacts: true
     - job: build_nuttx_app
       artifacts: false
